window.ChessLegendsData = {
  legends: [
    { surname: "Стейниц", photo: "Фотографии/1.Стейниц.png" },
    { surname: "Ласкер", photo: "Фотографии/2.Ласкер.png" },
    { surname: "Капабланка", photo: "Фотографии/3.Капабланка.png" },
    { surname: "Алехин", photo: "Фотографии/4.Алехин.jpg" },
    { surname: "Эйве", photo: "Фотографии/5.Эйве.png" },
    { surname: "Ботвинник", photo: "Фотографии/6.Ботвинник.png" },
    { surname: "Смыслов", photo: "Фотографии/7.Смыслов.png" },
    { surname: "Таль", photo: "Фотографии/8.Таль.png" },
    { surname: "Петросян", photo: "Фотографии/9.Петросян.png" },
    { surname: "Спасский", photo: "Фотографии/10.Спасский.jpg" },
    { surname: "Фишер", photo: "Фотографии/11.Фишер.jpg" },
    { surname: "Карпов", photo: "Фотографии/12.Карпов.png" },
    { surname: "Каспаров", photo: "Фотографии/13.Каспаров.jpg" },
    { surname: "Крамник", photo: "Фотографии/14.Крамник.jpg" },
    { surname: "Ананд", photo: "Фотографии/15.Ананд.jpeg" },
    { surname: "Карлсен", photo: "Фотографии/16.Карлсен.jpg" },
    { surname: "Дин Лижень", photo: "Фотографии/17.Дин Лижень.jpg" },
    { surname: "Морфи", photo: "Фотографии/18.Морфи.jpg" },
    { surname: "Андерсен", photo: "Фотографии/19.Андерсен.png" },
    { surname: "Рубинштейн", photo: "Фотографии/20.Рубинштейн.jpg" },
    { surname: "Бронштейн", photo: "Фотографии/21.Бронштейн.jpg" },
    { surname: "Керес", photo: "Фотографии/22.Керес.png" },
    { surname: "Корчной", photo: "Фотографии/23.Корчной.png" },
    { surname: "Иванчук", photo: "Фотографии/24.Иванчук.jpg" },
    { surname: "Топалов", photo: "Фотографии/25.Топалов.jpg" },
    { surname: "Свидлер", photo: "Фотографии/26.Свидлер.jpg" },
    { surname: "Полгар", photo: "Фотографии/27.Полгар.jpg" },
    { surname: "Аронян", photo: "Фотографии/28.Аронян.jpg" },
    { surname: "Мамедьяров", photo: "Фотографии/29.Мамедьяров.jpg" },
    { surname: "Накамура", photo: "Фотографии/30.Накамура.jpg" },
    { surname: "Каруана", photo: "Фотографии/31.Каруана.jpg" },
    { surname: "Непомнящий", photo: "Фотографии/32.Непомнящий.jpg" }
  ],
  difficultySettings: {
    "Начинающий": { pairs: 8, columns: 4 },
    "КМС": { pairs: 16, columns: 8 },
    "Мастер": { pairs: 24, columns: 12 },
    "Гроссмейстер": { pairs: 32, columns: 12 }
  }
};
