window.ChessLegendsBiographies = [
  { id: "steinitz", nameRu: "Вильгельм Стейниц", surnameRu: "Стейниц", photo: "assets/photos/commons/01-steinitz.jpg", fileRu: "content/biographies/ru/steinitz.md" },
  { id: "lasker", nameRu: "Эмануил Ласкер", surnameRu: "Ласкер", photo: "assets/photos/commons/02-lasker.jpg", fileRu: "content/biographies/ru/lasker.md" },
  { id: "capablanca", nameRu: "Хосе Рауль Капабланка", surnameRu: "Капабланка", photo: "assets/photos/commons/03-capablanca.jpg", fileRu: "content/biographies/ru/capablanca.md" },
  { id: "alekhine", nameRu: "Александр Алехин", surnameRu: "Алехин", photo: "assets/photos/commons/04-alekhine.jpg", fileRu: "content/biographies/ru/alekhine.md" },
  { id: "euwe", nameRu: "Макс Эйве", surnameRu: "Эйве", photo: "assets/photos/commons/05-euwe.jpg", fileRu: "content/biographies/ru/euwe.md" },
  { id: "botvinnik", nameRu: "Михаил Ботвинник", surnameRu: "Ботвинник", photo: "assets/photos/commons/06-botvinnik.jpg", fileRu: "content/biographies/ru/botvinnik.md" },
  { id: "smyslov", nameRu: "Василий Смыслов", surnameRu: "Смыслов", photo: "assets/photos/commons/07-smyslov.jpg", fileRu: "content/biographies/ru/smyslov.md" },
  { id: "tal", nameRu: "Михаил Таль", surnameRu: "Таль", photo: "assets/photos/commons/08-tal.jpg", fileRu: "content/biographies/ru/tal.md" },
  { id: "petrosian", nameRu: "Тигран Петросян", surnameRu: "Петросян", photo: "assets/photos/commons/09-petrosian.jpg", fileRu: "content/biographies/ru/petrosian.md" },
  { id: "spassky", nameRu: "Борис Спасский", surnameRu: "Спасский", photo: "assets/photos/commons/10-spassky.jpg", fileRu: "content/biographies/ru/spassky.md" },
  { id: "fischer", nameRu: "Роберт Джеймс Фишер", surnameRu: "Фишер", photo: "assets/photos/commons/11-fischer.jpg", fileRu: "content/biographies/ru/fischer.md" },
  { id: "karpov", nameRu: "Анатолий Карпов", surnameRu: "Карпов", photo: "assets/photos/commons/12-karpov.jpg", fileRu: "content/biographies/ru/karpov.md" },
  { id: "kasparov", nameRu: "Гарри Каспаров", surnameRu: "Каспаров", photo: "assets/photos/commons/13-kasparov.jpg", fileRu: "content/biographies/ru/kasparov.md" },
  { id: "kramnik", nameRu: "Владимир Крамник", surnameRu: "Крамник", photo: "assets/photos/commons/14-kramnik.jpg", fileRu: "content/biographies/ru/kramnik.md" },
  { id: "anand", nameRu: "Вишванатан Ананд", surnameRu: "Ананд", photo: "assets/photos/commons/15-anand.jpeg", fileRu: "content/biographies/ru/anand.md" },
  { id: "carlsen", nameRu: "Магнус Карлсен", surnameRu: "Карлсен", photo: "assets/photos/commons/16-carlsen.jpg", fileRu: "content/biographies/ru/carlsen.md" },
  { id: "ding-liren", nameRu: "Дин Лижэнь", surnameRu: "Дин Лижэнь", photo: "assets/photos/commons/17-ding-liren.jpg", fileRu: "content/biographies/ru/ding-liren.md" },
  { id: "gukesh", nameRu: "Гукеш Доммараджу", surnameRu: "Гукеш", photo: "assets/photos/commons/18-gukesh.jpg", fileRu: "content/biographies/ru/gukesh.md" },
  { id: "morphy", nameRu: "Пол Морфи", surnameRu: "Морфи", photo: "assets/photos/commons/18-morphy.jpg", fileRu: "content/biographies/ru/morphy.md" },
  { id: "anderssen", nameRu: "Адольф Андерсен", surnameRu: "Андерсен", photo: "assets/photos/commons/19-anderssen.jpg", fileRu: "content/biographies/ru/anderssen.md" },
  { id: "rubinstein", nameRu: "Акиба Рубинштейн", surnameRu: "Рубинштейн", photo: "assets/photos/commons/20-rubinstein.png", fileRu: "content/biographies/ru/rubinstein.md" },
  { id: "bronstein", nameRu: "Давид Бронштейн", surnameRu: "Бронштейн", photo: "assets/photos/commons/21-bronstein.jpg", fileRu: "content/biographies/ru/bronstein.md" },
  { id: "keres", nameRu: "Пауль Керес", surnameRu: "Керес", photo: "assets/photos/commons/22-keres.jpg", fileRu: "content/biographies/ru/keres.md" },
  { id: "korchnoi", nameRu: "Виктор Корчной", surnameRu: "Корчной", photo: "assets/photos/commons/23-korchnoi.jpg", fileRu: "content/biographies/ru/korchnoi.md" },
  { id: "ivanchuk", nameRu: "Василий Иванчук", surnameRu: "Иванчук", photo: "assets/photos/commons/24-ivanchuk.jpg", fileRu: "content/biographies/ru/ivanchuk.md" },
  { id: "topalov", nameRu: "Веселин Топалов", surnameRu: "Топалов", photo: "assets/photos/commons/25-topalov.jpg", fileRu: "content/biographies/ru/topalov.md" },
  { id: "svidler", nameRu: "Пётр Свидлер", surnameRu: "Свидлер", photo: "assets/photos/commons/26-svidler.jpg", fileRu: "content/biographies/ru/svidler.md" },
  { id: "polgar", nameRu: "Юдит Полгар", surnameRu: "Полгар", photo: "assets/photos/commons/27-polgar.jpg", fileRu: "content/biographies/ru/polgar.md" },
  { id: "aronian", nameRu: "Левон Аронян", surnameRu: "Аронян", photo: "assets/photos/commons/28-aronian.jpg", fileRu: "content/biographies/ru/aronian.md" },
  { id: "nakamura", nameRu: "Хикару Накамура", surnameRu: "Накамура", photo: "assets/photos/commons/30-nakamura.jpg", fileRu: "content/biographies/ru/nakamura.md" },
  { id: "caruana", nameRu: "Фабиано Каруана", surnameRu: "Каруана", photo: "assets/photos/commons/31-caruana.jpg", fileRu: "content/biographies/ru/caruana.md" },
  { id: "nepomniachtchi", nameRu: "Ян Непомнящий", surnameRu: "Непомнящий", photo: "assets/photos/commons/32-nepomniachtchi.jpg", fileRu: "content/biographies/ru/nepomniachtchi.md" }
];
